name: vae
channels:
  - defaults
  - conda-forge
dependencies:
  - ipykernel=6.29.5
  - ipython=8.31.0
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.45
  - libpq=17.2
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libsqlite=3.47.2
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=257.2
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - lz4-c=1.10.0
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mistune=3.1.3
  - mpg123=1.32.9
  - munkres=1.1.4
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nspr=4.36
  - nss=3.107
  - numexpr=2.10.1
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.5.2
  - packaging=24.2
  - pandas=2.2.3
  - pandoc=3.7.0.2
  - pandocfilters=1.5.0
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=24.2
  - pixman=0.44.2
  - platformdirs=4.3.6
  - ply=3.11
  - prompt-toolkit=3.0.48
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio-client=17.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - pyparsing=3.2.1
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyside6=6.8.1
  - python=3.12.8
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-tzdata=2024.2
  - python_abi=3.12
  - pytz=2024.1
  - pywavelets=1.8.0
  - pyzmq=26.2.0
  - qhull=2020.2
  - qt-main=5.15.15
  - qt6-main=6.8.1
  - rav1e=0.6.6
  - readline=8.2
  - referencing=0.36.2
  - rpds-py=0.26.0
  - scikit-image=0.25.0
  - scikit-learn=1.6.1
  - scipy=1.14.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=72.1.0
  - sip=6.7.12
  - six=1.17.0
  - snappy=1.2.1
  - soupsieve=2.7
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - svt-av1=2.3.0
  - threadpoolctl=3.5.0
  - tifffile=2025.1.10
  - tinycss2=1.4.0
  - tk=8.6.13
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - unicodedata2=15.1.0
  - wayland=1.23.1
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - wheel=0.44.0
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.43
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - zeromq=4.3.5
  - zfp=1.0.1
  - zipp=3.21.0
  - zlib-ng=2.2.3
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - albucore==0.0.23
      - albumentations==2.0.0
      - annotated-types==0.7.0
      - array-record==0.6.0
      - astunparse==1.6.3
      - attrs==25.1.0
      - certifi==2024.12.14
      - charset-normalizer==3.4.1
      - click==8.1.8
      - dm-tree==0.1.9
      - docstring-parser==0.16
      - etils==1.11.0
      - flatbuffers==24.12.23
      - fsspec==2025.2.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - googleapis-common-protos==1.66.0
      - grpcio==1.69.0
      - h5py==3.12.1
      - idna==3.10
      - immutabledict==4.2.1
      - importlib-resources==6.5.2
      - jsonpath-rw==1.4.0
      - keras==3.8.0
      - libclang==18.1.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.4.1
      - mlcroissant==1.0.18
      - namex==0.0.8
      - natsort==8.4.0
      - numpy==2.0.2
      - nvidia-cublas-cu12==12.5.3.2
      - nvidia-cuda-cupti-cu12==12.5.82
      - nvidia-cuda-nvcc-cu12==12.5.82
      - nvidia-cuda-nvrtc-cu12==12.5.82
      - nvidia-cuda-runtime-cu12==12.5.82
      - nvidia-cudnn-cu12==9.3.0.75
      - nvidia-cufft-cu12==11.2.3.61
      - nvidia-curand-cu12==10.3.6.82
      - nvidia-cusolver-cu12==11.6.3.83
      - nvidia-cusparse-cu12==12.5.1.3
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.5.82
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.10.0.84
      - opt-einsum==3.4.0
      - optree==0.13.1
      - pandas-stubs==2.3.0.250703
      - promise==2.3
      - protobuf==5.29.3
      - pyarrow==19.0.0
      - pydantic==2.10.5
      - pydantic-core==2.27.2
      - pyyaml==6.0.2
      - rdflib==7.1.4
      - requests==2.32.3
      - rich==13.9.4
      - simple-parsing==0.1.7
      - simsimd==6.2.1
      - stringzilla==3.11.3
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.18.0
      - tensorflow-datasets==4.9.7
      - tensorflow-metadata==1.16.1
      - termcolor==2.5.0
      - toml==0.10.2
      - tqdm==4.67.1
      - types-pytz==2025.2.0.20250516
      - urllib3==2.3.0
      - werkzeug==3.1.3
      - wrapt==1.17.0
